version = 1


[merge]
method = "squash"
automerge_label = "automerge 🚀"

[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["dependabot"]

[approve]
auto_approve_usernames = ["dependabot"]
